version: '3.8'
services:
  mongodb:
    container_name: db
    image: mongo:latest
    ports:
      - '20001:27017'
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  bot:
    container_name: bot
    image: 'bot'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://db:27017/tgbot
volumes:
  mongo-data: